# Generated by Django 3.2 on 2021-06-02 09:52

import uuid

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('good_availability_threshold', models.PositiveIntegerField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('description', models.TextField(default='')),
                ('main_image_url', models.URLField(blank=True, null=True)),
                ('ean', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='EAN can contain only numbers', regex='[0-9]{13}')])),
                ('category', models.ManyToManyField(to='categories.Category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
