# Generated by Django 3.1.7 on 2021-05-16 17:56

from django.db import migrations, models
import easywarehouse.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210421_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, storage=easywarehouse.storage_backends.S3(), upload_to=''),
            preserve_default=False,
        ),
    ]
