# Generated by Django 3.2 on 2021-05-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_auto_20210525_0739"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="max_quantity",
            new_name="good_availability_threshold",
        ),
    ]
