# Generated by Django 3.2 on 2021-05-29 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_main_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(default='0000000000000', max_length=13, validators=[django.core.validators.RegexValidator(message='EAN can contain only numbers', regex='{13}[0-9]')]),
        ),
    ]
