# Generated by Django 3.2 on 2021-06-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210530_1532'),
        ('products', '0010_alter_product_ean'),
    ]

    operations = [
    ]
